Create Quizz + fix error in CreateQuestion/GetThemes + others details
DonatienGascoin/Top-Quizz pull request #14
Opened 2016-12-23 23:49 UTC by paretl

2016-12-24 17:18 UTC, DonatienGascoin requested changes

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/ChooseTheme.java
> -        if (themes != null && themes.size() != 0) {
Pourquoi avoir supprimé la ligne de test?

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/ChooseTheme.java
> +        Set set = new HashSet() ;
Pourquoi passer par une arrayList puis par un set puis par une arrayList? Fais uniquement un set, et au pire une list après, mais même pas besoin je pense

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/ChooseTheme.java
> +            myThemes = (ArrayList<Theme>) bundle.getSerializable(THEME);
Il manque le connectedUser

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/ChooseTheme.java
> +        startActivity(intent);
Passe le connectedUser

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuestion.java
> +            if(!"".equals(explanation)) {
Tu fais quoi dans le cas ou exapnation == ""? Si tu ne fais rien (ou qu'il n'y a pas de valeur par défaut) enlève le test, il est inutile

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuestion.java
> +            if(!"".equals(question)) {
Idem

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuestion.java
> +        if(connectedUser == null) {
Remonte le en haut de la fonction, pour ne pas faire de calcul inutile si il est null

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuestion.java
> +                    intent.putExtra(EXPLANATION, explanation);
Passe le connectedUser aussi

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuestion.java
> +        intent.putExtras(bundle);
Il y a quoi dans ton bundle? Ajoute un commentaire pour préciser, qu'on oublie pas

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +            if(!"".equals(bundle.getString(QUIZZNAME))) {
Idem, supprime le test si il n'est pas utile

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +            if(bundle.getInt(RANDOM) == 1) {
Idem, supprime le test si il n'est pas utile

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +
Vérifie si le connectedUser == null, et retourne sur la mainActivity si c'est le cas

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +                    intent.putExtras(bundle);
Precise le contenu du bundle please

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +                    intent.putExtra(RANDOM, randomQuestionButton.isChecked() ? 0 : 1);
Ajoute le connectedUser si il ne vient pas du bundle

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +            intent.putExtra(RANDOM, randomQuestionButton.isChecked() ? 0 : 1);
Ajoute le connectedUser

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +        intent.putExtras(bundle);
Precise stp

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +            if(myThemes.size() != 0) {
test si != null avant

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +                intent.putExtras(bundle);
Precise

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizzChoose.java
> +            intent.putExtra(QUESTIONS, questionsChoosed);
precise, ajoute bien le connectedUser

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizzChoose.java
> +            intent.putExtras(bundle);
Pareil x)

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/CreateQuizzChoose.java
> +        intent.putExtras(bundle);
Et encore pareil ;)

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/Home.java
> +                intent.putExtra(USER, connectedUser);
Ah... non pas la, rien à faire ;)

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/ShowQuestions.java
> +            connectedUser = (User) getIntent().getSerializableExtra(USER);
test si != null

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/ThemesDisplay.java
> +
A supprimer?

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/java/cpe/top/quizz/utils/ListViewAdapterThemes.java
> +                intent.putExtra(THEME, themeListChoosed);
Ajoute l'utilisateur

2016-12-24 17:18 UTC, DonatienGascoin commented on app/src/main/res/values/strings.xml
> +    <string-array name="theme_arrays">
C'est pour quoi faire ça?

2016-12-26 19:34 UTC, paretl commented on app/src/main/java/cpe/top/quizz/ChooseTheme.java
> +            myThemes = (ArrayList<Theme>) bundle.getSerializable(THEME);
done

2016-12-26 19:34 UTC, paretl commented on app/src/main/java/cpe/top/quizz/ChooseTheme.java
> -        if (themes != null && themes.size() != 0) {
elle est juste en dessous

2016-12-26 19:35 UTC, paretl commented on app/src/main/java/cpe/top/quizz/ChooseTheme.java
> +        startActivity(intent);
Il est dans le bundle

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuestion.java
> +            if(!"".equals(explanation)) {
Si il est utile, il permet de récup la valeur de explanation si j'ai changé d'activité entre temps (comme ça elle est pas perdu)

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuestion.java
> +            if(!"".equals(question)) {
pareil qu'en haut

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuestion.java
> +        if(connectedUser == null) {
done

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuestion.java
> +                    intent.putExtra(EXPLANATION, explanation);
Dans le bundle ;)

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuestion.java
> +        intent.putExtras(bundle);
ok j'ajoute des coms un peu partout pour préciser el contenu de chaque bundle

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +
done

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +            if(!"".equals(bundle.getString(QUIZZNAME))) {
pareil c'est pour recup la valeur si on change d'activité

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +            if(bundle.getInt(RANDOM) == 1) {
idem

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +            if(myThemes.size() != 0) {
done

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +                    intent.putExtra(RANDOM, randomQuestionButton.isChecked() ? 0 : 1);
il est dans le bundle

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +                    intent.putExtras(bundle);
ok

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +            intent.putExtra(RANDOM, randomQuestionButton.isChecked() ? 0 : 1);
in the bundle

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +                intent.putExtras(bundle);
ok

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizz.java
> +        intent.putExtras(bundle);
ok

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizzChoose.java
> +            intent.putExtra(QUESTIONS, questionsChoosed);
in the bundle

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizzChoose.java
> +            intent.putExtras(bundle);
in the bundle

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/CreateQuizzChoose.java
> +        intent.putExtras(bundle);
in the bundle

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/Home.java
> +                intent.putExtra(USER, connectedUser);
pas dans le bundle mais oui :p

2016-12-26 20:36 UTC, paretl commented on app/src/main/java/cpe/top/quizz/utils/ListViewAdapterThemes.java
> +                intent.putExtra(THEME, themeListChoosed);
in the bundle

2016-12-26 20:36 UTC, paretl commented on app/src/main/res/values/strings.xml
> +    <string-array name="theme_arrays">
ca dégage

2016-12-26 20:37 UTC, merged